### ISSUE TITLE
Clay's Picture not showing up

### ISSUE THREAD

**Issue by jateeter** [Maalka/maalka-semantic.github.com#3]
Maalka/maalka-semantic.github.com - Clay's picture is not displaying on my machine

**Comment by hendrime** [comment]
Is it being hosted right now?

**Comment by jateeter** [comment]
yep - http://maalka.github.io/maalka-semantic 
(and the problem with clay's picture is the css references clay_round.png (and Clay_round.png or clay_round.jpg are the two choices I think).

**Comment by jateeter** [comment]
Closed with commit: https://github.com/Maalka/maalka-semantic.github.com/commit/4865b7d87cdc4f6a10700144063eeaa33f5850d0
